-- ============================================================
-- Supabase Setup Script & RLS Fix for Flute Notation Database
-- ============================================================
-- Copy and paste this script into your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/kjmqfkhngvuvivtqmjko/sql
-- ============================================================

-- RLS FIX FOR EXISTING "Songs" OR "songs" TABLE:
-- If you already created a table named "Songs" or "songs" in Supabase,
-- run these RLS policy commands to allow public read access:

ALTER TABLE IF EXISTS public."Songs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read on Songs" ON public."Songs";
CREATE POLICY "Allow public read on Songs" ON public."Songs" FOR SELECT TO public USING (true);

ALTER TABLE IF EXISTS public.songs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on songs" ON public.songs;
CREATE POLICY "Allow public read access on songs" ON public.songs FOR SELECT TO public USING (true);


-- 1. Create default `songs` table (if not already created)
CREATE TABLE IF NOT EXISTS public.songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_name TEXT NOT NULL,
    artist TEXT,
    movie TEXT,
    scale TEXT DEFAULT 'G Major',
    flute_type TEXT DEFAULT '6-Hole Flute',
    lyrics JSONB DEFAULT '[]'::jsonb,
    notation JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert Sample Songs with Sargam Flute Notations
INSERT INTO public.songs (song_name, artist, movie, scale, flute_type, lyrics, notation)
VALUES 
(
    'Kannuladha',
    'Anirudh Ravichander',
    '3 (Three)',
    'G Major',
    'Bansuri',
    '["Kannuladha", "Aasaladha", "Buggaladha", "Mudduladha"]'::jsonb,
    '[
        {"line": "DA GA GA DA DA", "lyric": "Kannuladha"},
        {"line": "DA GA GA DA PA", "lyric": "Aasaladha"},
        {"line": "DA GA GA DA DA", "lyric": "Buggaladha"},
        {"line": "DA GA GA DA PA", "lyric": "Mudduladha"}
    ]'::jsonb
),
(
    'River Song',
    'Hariprasad Chaurasia',
    'Flowing Waters',
    'G Major',
    '6-Hole Flute',
    '["Flowing waters, singing free,", "Dancing waves for you and me,", "Under skies of blue and gold,", "Stories by the river told."]'::jsonb,
    '[
        {"line": "Pa Pa Dha | Ni Sa'' Ni | Dha Pa Ma | Ga Ma Pa", "lyric": "Flow-ing wa-ters, sing-ing free,"},
        {"line": "Pa Ma Ga | Re Ga Ma | Ma Ga Re | Sa -- --", "lyric": "Dan-cing waves for you and me,"},
        {"line": "Sa Re Ga | Ma Pa Dha | Ni Dha Pa | Ma Ga Re", "lyric": "Un-der skies of blue and gold,"},
        {"line": "Re Ma Ga | Re Sa Ni | Sa Re Ga | Sa -- --", "lyric": "Sto-ries by the ri-ver told."}
    ]'::jsonb
),
(
    'Twilight Melody',
    'Shivkumar Sharma',
    'Evening Raga',
    'D Minor',
    '6-Hole Flute',
    '["As twilight fades and stars appear,", "A melody drifts soft and clear,", "The flute sings out across the night,", "Filling the world with golden light."]'::jsonb,
    '[
        {"line": "Ga Ma Dha | Ni Sa'' Re'' | Sa'' Ni Dha | Pa Ma Ga", "lyric": "As twi-light fades and stars ap-pear,"},
        {"line": "Ma Ga Re | Sa Ni Dha | Pa Ma Ga | Re Sa --", "lyric": "A me-lo-dy drifts soft and clear,"},
        {"line": "Sa Re Ma | Ga Ma Pa | Dha Ni Sa'' | Ni Dha Pa", "lyric": "The flute sings out a-cross the night,"},
        {"line": "Ma Pa Dha | Ni Sa'' -- | Re'' Sa'' Ni | Sa'' -- --", "lyric": "Fill-ing the world with gold-en light."}
    ]'::jsonb
),
(
    'Kesariya',
    'Arijit Singh',
    'Brahmastra',
    'C Major',
    'Bansuri C Middle',
    '["Mujhko itna bataaye koi", "Kaise tujhse dil na lagaaye koi", "Kesariya tera ishq hai piya"]'::jsonb,
    '[
        {"line": "Sa Re Ga Ma Pa | Pa Ma Ga Re Sa", "lyric": "Mujhko itna bataaye koi"},
        {"line": "Sa Re Ga Ma Pa | Pa Dha Pa Ma Ga", "lyric": "Kaise tujhse dil na lagaaye koi"},
        {"line": "Pa Dha Ni Sa'' | Sa'' Ni Dha Pa Ma", "lyric": "Kesariya tera ishq hai piya"}
    ]'::jsonb
)
ON CONFLICT DO NOTHING;
